### ISSUE TITLE
Request for Detailed Instructions on Running the Code

### ISSUE THREAD

**Issue by vangao** [stevebottos/owl-vit-object-detection#4]
Hello Steve,

I hope this message finds you well. I am reaching out to you regarding your GitHub repository, 'owl-vit-object-detection'. I am deeply interested in your project and would like to learn more about it.

However, I am finding some difficulties in running the code and I believe a more detailed guide or instructions would be greatly helpful.

Your work on 'owl-vit-object-detection' is truly impressive and I'm eager to delve deeper into it. I understand that writing such instructions can be time-consuming, but it would be of tremendous help to me and possibly to other users as well.

Thank you in advance for your time and consideration. I look forward to hearing from you.

Best regards,
Van Gao

**Comment by stevebottos** [comment]
Hey @vangao , I haven't touched this project for a long time but I do plan to revisit it soon and make some updates which include a readme for how to get started. Please watch the repo so that you can stay updated! It's a busy summer for me so it might be a while.

**Comment by stevebottos** [comment]
@vangao Have a look now

**Comment by vangao** [comment]
Hi Steve,

Just a quick note to say thanks for all your help with the 'owl-vit-object-detection' project. It's made a huge difference and I really appreciate it.
